name: smart_downloader
description: "Smart video downloader with queue management"
publish_to: 'none'
version: 2.2.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  window_manager: ^0.4.3
  path_provider: ^2.1.5
  shared_preferences: ^2.3.4
  package_info_plus: ^8.2.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/src/assets/icons/
